version: '3.3'
services:
  redis:
    image: redis:7.0.12
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data
      - ./conf/redis.config:/etc/redis/redis.config
      - ./logs:/var/log/redis
    command: ["redis-server","/etc/redis/redis.config"]